# The values in this file should be changed
apiVersion: v1
kind: Secret
metadata:
  name: danswer-secrets
type: Opaque
data:
  postgres_user: cG9zdGdyZXM= # "postgres" base64 encoded
  postgres_password: cGFzc3dvcmQ= # "password" base64 encoded
  # postgres_password: OWIzMjA4MGJjNDM3NjA4Yjc1NDA0MzgxMGM3OTIxNDM2MTIwZjlhMDczZmJjNTQ2MTY1NGIyMDcyYmUyNGVlYgo= # "password" base64 encoded
  google_oauth_client_id: # You will need to provide this, use echo -n "your-client-id" | base64
  google_oauth_client_secret: # You will need to provide this, use echo -n "your-client-id" | base64
