apiVersion: v1
kind: Service
metadata:
  name: document-index-service
spec:
  selector:
    app: vespa
  ports:
    - name: vespa-tenant-port
      protocol: TCP
      port: 19071
      targetPort: 19071
    - name: vespa-port
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa
  labels:
    app: vespa
spec:
  replicas: 1
  serviceName: vespa
  selector:
    matchLabels:
      app: vespa
  template:
    metadata:
      labels:
        app: vespa
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/sdsu-llm
                operator: Exists
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-80GB-PCIe
              - key: nautilus.io/linstor
                operator: Exists
      containers:
      - name: vespa
        image: vespaengine/vespa:8.277.17
        command: ["/bin/bash", "-c", "/opt/vespa/bin/vespa-start-configserver && /opt/vespa/bin/vespa-start-services && /opt/vespa/bin/vespa-logfmt --follow --format \"$VESPA_LOG_FORMAT\""]
        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            memory: 4Gi
            cpu: 2
        imagePullPolicy: IfNotPresent
        securityContext:
          # privileged: true
          runAsUser: 0
        ports:
        - containerPort: 19071
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /state/v1/health
            port: 19071
            scheme: HTTP
        volumeMounts:
        - name: vespa-storage
          mountPath: /opt/vespa/var/
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/sdsu-fix
        operator: Exists
      - effect: NoSchedule
        key: nautilus.io/csu-tide
        operator: Exists
      - effect: NoSchedule
        key: nautilus.io/sdsu-llm
        operator: Exists
  volumeClaimTemplates:
  - metadata:
      name: vespa-storage
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: linstor-sdsu
      resources:
        requests:
          # Adjust the storage request size as needed.
          storage: 5Gi
